<?php

namespace Fin\FinanceBundle\Repository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExpenses($page = 1, $per_page, $count_only = false)
    {
        $qb = $this->createQueryBuilder('e');      
      
        $query = $qb->getQuery();
        $items = $query->getResult();
        $total_count = count($items);
//        $total_count = $query->getSingleScalarResult();

        if ($count_only) {
            return $total_count;
        }

        $qb->orderBy('e.created_at', 'asc');

        if (ceil($total_count / $per_page) < $page) {
            $page = ceil($total_count / $per_page) == 0 ? 1 : ceil($total_count / $per_page);
        }

        $offset = ($page - 1) * $per_page;

        if($per_page)
        {
          $qb->setMaxResults($per_page);
        }
        if($offset)
        {
          $qb->setFirstResult($offset);
        }

        $query = $qb->getQuery();
        $items = $query->getResult();

        return array('total_count' => $total_count, 'items' => $items);
    }
}
