<?php

namespace Fin\FinanceBundle\Repository;

/**
 * ExpenseItemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseItemCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
