<?php

namespace Fin\FinanceBundle\Repository;

/**
 * ExpenseItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseItemRepository extends \Doctrine\ORM\EntityRepository
{
}
