<?php

namespace Fin\FinanceBundle\Repository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExpenses($max = null, $offset = null)
    {
      $qb = $this->createQueryBuilder('e')
        ->orderBy('e.created_at', 'DESC');

      if($max)
      {
        $qb->setMaxResults($max);
      }

      if($offset)
      {
        $qb->setFirstResult($offset);
      }

      $query = $qb->getQuery();

      return $query->getResult();
    }
}
