<?php

namespace Fin\FinanceBundle\Repository;

/**
 * IncomeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeItemRepository extends \Doctrine\ORM\EntityRepository
{
}
