<?php

namespace Fin\FinanceBundle\Repository;

/**
 * IncomeItemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeItemCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
