Fin\FinanceBundle\Entity\IncomeItem:
    type: entity
    repositoryClass: Fin\FinanceBundle\Repository\IncomeItemRepository
    table: income_item
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            length: 255
            unique: true
    manyToOne:
        expense_item_category:
            targetEntity: IncomeItemCategory
            inversedBy: income_item
            joinColumn:
                name: category_id
                referencedColumnName: id
        
